### ISSUE TITLE
This project cannot be clicked through transparent windows

### ISSUE THREAD

**Issue by Vision-996** [noahswtf/external-overlay#2]

**Comment by noahswtf** [comment]
When the gui is enabled, we apply the WS_EX_TOPMOST flag, which makes it the foreground window, and as the window is the same size as the monitor, it means that when the gui is enabled, it takes priority. If you would like to make it click-through, then apply the WS_EX_LAYERED flag alongside the WS_EX_TRANSPARENT flag, which allows clicks to pass through to other windows (which is what we do once gui is not enabled).

This is seen here:

```cpp
if (overlay::enabled)
{
    overlay::draw_gui();
    SetWindowLong(hwnd, GWL_EXSTYLE, WS_EX_TOPMOST);
}
else
{
    SetWindowLong(hwnd, GWL_EXSTYLE, WS_EX_TRANSPARENT | WS_EX_LAYERED);
}
```

**Comment by ChickenPige0n** [comment]
are there any way to make the non-transparent part being clickable while other part can be clicked through?
